-- JIS Appellate Workflow Schema: Lower Court -> High Court -> Supreme Court

CREATE TABLE IF NOT EXISTS case_appeals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  original_case_id INT NOT NULL,
  appeal_case_id INT NOT NULL,
  appeal_level ENUM('DISTRICT_TO_HIGH_COURT', 'HIGH_COURT_TO_SUPREME_COURT', 'SUBORDINATE_TO_HIGH_COURT', 'SUBORDINATE_TO_DISTRICT') NOT NULL,
  originating_court_level_id INT NOT NULL,
  destination_court_level_id INT NOT NULL,
  destination_high_court_id INT NULL,
  destination_bench_id INT NULL,
  destination_district_id INT NULL,
  appeal_type VARCHAR(150) NOT NULL,
  governing_statute VARCHAR(255) NULL,
  filing_date DATE NOT NULL,
  status ENUM('Filed', 'Admitted', 'Pending', 'Disposed', 'Withdrawn') NOT NULL DEFAULT 'Filed',
  grounds TEXT NULL,
  is_synthetic TINYINT(1) NOT NULL DEFAULT 0,
  provenance VARCHAR(50) NOT NULL DEFAULT 'STAFF_FILED',
  created_by INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (original_case_id) REFERENCES cases(id) ON DELETE CASCADE,
  FOREIGN KEY (appeal_case_id) REFERENCES cases(id) ON DELETE CASCADE,
  FOREIGN KEY (originating_court_level_id) REFERENCES court_levels(id) ON DELETE RESTRICT,
  FOREIGN KEY (destination_court_level_id) REFERENCES court_levels(id) ON DELETE RESTRICT,
  FOREIGN KEY (destination_high_court_id) REFERENCES high_courts(id) ON DELETE SET NULL,
  FOREIGN KEY (destination_bench_id) REFERENCES high_court_benches(id) ON DELETE SET NULL,
  FOREIGN KEY (destination_district_id) REFERENCES districts(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
  UNIQUE KEY uk_original_appeal (original_case_id, appeal_case_id),
  INDEX idx_ca_original (original_case_id),
  INDEX idx_ca_appeal (appeal_case_id),
  INDEX idx_ca_status (status),
  INDEX idx_ca_level (appeal_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
