'use strict';

/**
 * IPC (Indian Penal Code, 1860) Chapters and Complete Section Library (Sec 1 to 511)
 * Historical validity: 1862-01-01 to 2024-06-30
 */

const IPC_CHAPTERS = [
  { chapter_number: 'Chapter I', title: 'Introduction', chapter_order: 1, range: [1, 5] },
  { chapter_number: 'Chapter II', title: 'General Explanations', chapter_order: 2, range: [6, 52] },
  { chapter_number: 'Chapter III', title: 'Of Punishments', chapter_order: 3, range: [53, 75] },
  { chapter_number: 'Chapter IV', title: 'General Exceptions', chapter_order: 4, range: [76, 106] },
  { chapter_number: 'Chapter V', title: 'Of Abetment', chapter_order: 5, range: [107, 120] },
  { chapter_number: 'Chapter VA', title: 'Criminal Conspiracy', chapter_order: 6, range: ['120A', '120B'] },
  { chapter_number: 'Chapter VI', title: 'Of Offences Against the State', chapter_order: 7, range: [121, 130] },
  { chapter_number: 'Chapter VII', title: 'Of Offences Relating to the Army, Navy and Air Force', chapter_order: 8, range: [131, 140] },
  { chapter_number: 'Chapter VIII', title: 'Of Offences Against the Public Tranquillity', chapter_order: 9, range: [141, 160] },
  { chapter_number: 'Chapter IX', title: 'Of Offences by or Relating to Public Servants', chapter_order: 10, range: [161, 171] },
  { chapter_number: 'Chapter IXA', title: 'Of Offences Relating to Elections', chapter_order: 11, range: ['171A', '171I'] },
  { chapter_number: 'Chapter X', title: 'Of Contempts of the Lawful Authority of Public Servants', chapter_order: 12, range: [172, 190] },
  { chapter_number: 'Chapter XI', title: 'Of False Evidence and Offences Against Public Justice', chapter_order: 13, range: [191, 229] },
  { chapter_number: 'Chapter XII', title: 'Of Offences Relating to Coin and Government Stamps', chapter_order: 14, range: [230, 263] },
  { chapter_number: 'Chapter XIII', title: 'Of Offences Relating to Weights and Measures', chapter_order: 15, range: [264, 267] },
  { chapter_number: 'Chapter XIV', title: 'Of Offences Affecting the Public Health, Safety, Convenience, Decency and Morals', chapter_order: 16, range: [268, 294] },
  { chapter_number: 'Chapter XV', title: 'Of Offences Relating to Religion', chapter_order: 17, range: [295, 298] },
  { chapter_number: 'Chapter XVI', title: 'Of Offences Affecting the Human Body', chapter_order: 18, range: [299, 377] },
  { chapter_number: 'Chapter XVII', title: 'Of Offences Against Property', chapter_order: 19, range: [378, 462] },
  { chapter_number: 'Chapter XVIII', title: 'Of Offences Relating to Documents and to Property Marks', chapter_order: 20, range: [463, 489] },
  { chapter_number: 'Chapter XIX', title: 'Of the Criminal Breach of Contracts of Service', chapter_order: 21, range: [490, 492] },
  { chapter_number: 'Chapter XX', title: 'Of Offences Relating to Marriage', chapter_order: 22, range: [493, 498] },
  { chapter_number: 'Chapter XXA', title: 'Of Cruelty by Husband or Relatives of Husband', chapter_order: 23, range: ['498A', '498A'] },
  { chapter_number: 'Chapter XXI', title: 'Of Defamation', chapter_order: 24, range: [499, 502] },
  { chapter_number: 'Chapter XXII', title: 'Of Criminal Intimidation, Insult and Annoyance', chapter_order: 25, range: [503, 510] },
  { chapter_number: 'Chapter XXIII', title: 'Of Attempts to Commit Offences', chapter_order: 26, range: [511, 511] }
];

// Specific known section titles for IPC
const IPC_SECTION_TITLES = {
  '1': 'Title and extent of operation of the Code',
  '2': 'Punishment of offences committed within India',
  '3': 'Punishment of offences committed beyond, but which by law may be tried within, India',
  '4': 'Extension of Code to extra-territorial offences',
  '5': 'Certain laws not to be affected by this Act',
  '6': 'Definitions in the Code to be understood subject to exceptions',
  '7': 'Sense of expression once explained',
  '8': 'Gender',
  '9': 'Number',
  '10': 'Man, Woman',
  '11': 'Person',
  '12': 'Public',
  '13': 'Queen (Repealed)',
  '14': 'Servant of Government',
  '15': 'British India (Repealed)',
  '16': 'Government of India (Repealed)',
  '17': 'Government',
  '18': 'India',
  '19': 'Judge',
  '20': 'Court of Justice',
  '21': 'Public servant',
  '22': 'Movable property',
  '23': 'Wrongful gain, Wrongful loss',
  '24': 'Dishonestly',
  '25': 'Fraudulently',
  '26': 'Reason to believe',
  '27': 'Property in possession of wife, clerk or servant',
  '28': 'Counterfeit',
  '29': 'Document',
  '29A': 'Electronic record',
  '30': 'Valuable security',
  '31': 'A will',
  '32': 'Words referring to acts include illegal omissions',
  '33': 'Act, Omission',
  '34': 'Acts done by several persons in furtherance of common intention',
  '35': 'When such an act is criminal by reason of its being done with a criminal knowledge or intention',
  '36': 'Effect caused partly by act and partly by omission',
  '37': 'Co-operation by doing one of several acts constituting an offence',
  '38': 'Persons concerned in criminal act may be guilty of different offences',
  '39': 'Voluntarily',
  '40': 'Offence',
  '41': 'Special law',
  '42': 'Local law',
  '43': 'Illegal, Legally bound to do',
  '44': 'Injury',
  '45': 'Life',
  '46': 'Death',
  '47': 'Animal',
  '48': 'Vessel',
  '49': 'Year, Month',
  '50': 'Section',
  '51': 'Oath',
  '52': 'Good faith',
  '52A': 'Harbour',
  '53': 'Punishments',
  '53A': 'Construction of reference to transportation',
  '54': 'Commutation of sentence of death',
  '55': 'Commutation of sentence of imprisonment for life',
  '55A': 'Definition of appropriate Government',
  '57': 'Fractions of terms of punishment',
  '60': 'Sentence may be (in certain cases of imprisonment) wholly or partly rigorous or simple',
  '63': 'Amount of fine',
  '64': 'Sentence of imprisonment for non-payment of fine',
  '65': 'Limit to imprisonment for non-payment of fine, when imprisonment and fine awardable',
  '66': 'Description of imprisonment for non-payment of fine',
  '67': 'Imprisonment for non-payment of fine, when offence punishable with fine only',
  '70': 'Fine leviable within six years, or during imprisonment',
  '71': 'Limit of punishment of offence made up of several offences',
  '72': 'Punishment of person guilty of one of several offences, the judgment stating that it is doubtful of which',
  '73': 'Solitary confinement',
  '74': 'Limit of solitary confinement',
  '75': 'Enhanced punishment for certain offences under Chapter XII or Chapter XVII after previous conviction',
  '76': 'Act done by a person bound, or by mistake of fact believing himself bound, by law',
  '77': 'Act of Judge when acting judicially',
  '78': 'Act done pursuant to the judgment or order of Court',
  '79': 'Act done by a person justified, or by mistake of fact believing himself justified, by law',
  '80': 'Accident in doing a lawful act',
  '81': 'Act likely to cause harm, but done without criminal intent, and to prevent other harm',
  '82': 'Act of a child under seven years of age (Doli incapax)',
  '83': 'Act of a child above seven and under twelve of immature understanding',
  '84': 'Act of a person of unsound mind (McNaughten Rule)',
  '85': 'Act of a person incapable of judgment by reason of intoxication caused against his will',
  '86': 'Offence requiring a particular intent or knowledge committed by one who is intoxicated',
  '87': 'Act not intended and not known to be likely to cause death or grievous hurt, done by consent',
  '88': 'Act not intended to cause death, done by consent in good faith for person’s benefit',
  '89': 'Act done in good faith for benefit of child or insane person, by or by consent of guardian',
  '90': 'Consent known to be given under fear or misconception',
  '91': 'Exclusion of acts which are offences independently of harm caused',
  '92': 'Act done in good faith for benefit of a person without consent',
  '93': 'Communication made in good faith',
  '94': 'Act to which a person is compelled by threats',
  '95': 'Act causing slight harm (De minimis non curat lex)',
  '96': 'Things done in private defence',
  '97': 'Right of private defence of the body and of property',
  '98': 'Right of private defence against act of a person of unsound mind, etc.',
  '99': 'Acts against which there is no right of private defence',
  '100': 'When the right of private defence of the body extends to causing death',
  '101': 'When such right extends to causing any harm other than death',
  '102': 'Commencement and continuance of the right of private defence of the body',
  '103': 'When the right of private defence of property extends to causing death',
  '104': 'When such right extends to causing any harm other than death',
  '105': 'Commencement and continuance of the right of private defence of property',
  '106': 'Right of private defence against deadly assault when there is risk of harm to innocent person',
  '107': 'Abetment of a thing',
  '108': 'Abettor',
  '108A': 'Abetment in India of offences outside India',
  '109': 'Punishment of abetment if the act abetted is committed in consequence and where no express provision is made for its punishment',
  '110': 'Punishment of abetment if person abetted does act with different intention from that of abettor',
  '111': 'Liability of abettor when one act abetted and different act done',
  '112': 'Abettor when liable to cumulative punishment for act abetted and for act done',
  '113': 'Liability of abettor for an effect caused by the act abetted different from that intended by the abettor',
  '114': 'Abettor present when offence is committed',
  '115': 'Abetment of offence punishable with death or imprisonment for life',
  '116': 'Abetment of offence punishable with imprisonment',
  '117': 'Abetting commission of offence by the public or by more than ten persons',
  '118': 'Concealing design to commit offence punishable with death or imprisonment for life',
  '119': 'Public servant concealing design to commit offence which it is his duty to prevent',
  '120': 'Concealing design to commit offence punishable with imprisonment',
  '120A': 'Definition of criminal conspiracy',
  '120B': 'Punishment of criminal conspiracy',
  '121': 'Waging, or attempting to wage war, or abetting waging of war, against the Government of India',
  '121A': 'Conspiracy to commit offences punishable by section 121',
  '122': 'Collecting arms, etc., with intention of waging war against the Government of India',
  '123': 'Concealing with intent to facilitate design to wage war',
  '124': 'Assaulting President, Governor, etc., with intent to compel or restrain the exercise of any lawful power',
  '124A': 'Sedition',
  '125': 'Waging war against any Asiatic Power in alliance with the Government of India',
  '128': 'Public servant voluntarily allowing prisoner of State or war to escape',
  '130': 'Aiding escape of, rescuing or harbouring such prisoner',
  '141': 'Unlawful assembly',
  '142': 'Being member of unlawful assembly',
  '143': 'Punishment for unlawful assembly',
  '144': 'Joining unlawful assembly armed with deadly weapon',
  '145': 'Joining or continuing in unlawful assembly, knowing it has been commanded to disperse',
  '146': 'Rioting',
  '147': 'Punishment for rioting',
  '148': 'Rioting, armed with deadly weapon',
  '149': 'Every member of unlawful assembly guilty of offence committed in prosecution of common object',
  '150': 'Hiring, or conniving at hiring, of persons to join unlawful assembly',
  '151': 'Knowingly joining or continuing in assembly of five or more persons after it has been commanded to disperse',
  '152': 'Assaulting or obstructing public servant when suppressing riot, etc.',
  '153': 'Wantonly giving provocation with intent to cause riot',
  '153A': 'Promoting enmity between different groups on ground of religion, race, place of birth, residence, language, etc., and doing acts prejudicial to maintenance of harmony',
  '153B': 'Imputations, assertions prejudicial to national-integration',
  '159': 'Affray',
  '160': 'Punishment for committing affray',
  '161': 'Public servant taking gratification other than legal remuneration in respect of an official act (Repealed)',
  '166': 'Public servant disobeying law, with intent to cause injury to any person',
  '166A': 'Public servant disobeying direction under law',
  '167': 'Public servant framing an incorrect document with intent to cause injury',
  '171A': 'Candidate, Electoral right defined',
  '171B': 'Bribery at elections',
  '171C': 'Undue influence at elections',
  '171D': 'Personation at elections',
  '171E': 'Punishment for bribery',
  '171F': 'Punishment for undue influence or personation at an election',
  '171G': 'False statement in connection with an election',
  '171H': 'Illegal payments in connection with an election',
  '171I': 'Failure to keep election accounts',
  '172': 'Absconding to avoid service of summons or other proceeding',
  '173': 'Preventing service of summons or other proceeding, or preventing publication thereof',
  '174': 'Non-attendance in obedience to an order from public servant',
  '174A': 'Non-appearance in response to a proclamation under section 82 of Act 2 of 1974',
  '175': 'Omission to produce document to public servant by person legally bound to produce it',
  '177': 'Furnishing false information',
  '182': 'False information, with intent to cause public servant to use his lawful power to the injury of another person',
  '186': 'Obstructing public servant in discharge of public functions',
  '187': 'Omission to assist public servant when bound by law to give assistance',
  '188': 'Disobedience to order duly promulgated by public servant',
  '191': 'Giving false evidence (Perjury)',
  '192': 'Fabricating false evidence',
  '193': 'Punishment for false evidence',
  '194': 'Giving or fabricating false evidence with intent to procure conviction of capital offence',
  '195': 'Giving or fabricating false evidence with intent to procure conviction of offence punishable with imprisonment for life or imprisonment',
  '195A': 'Threatening any person to give false evidence',
  '201': 'Causing disappearance of evidence of offence, or giving false information to screen offender',
  '202': 'Intentional omission to give information of offence by person bound to inform',
  '204': 'Destruction of document or electronic record to prevent its production as evidence',
  '211': 'False charge of offence made with intent to injure',
  '212': 'Harbouring offender',
  '216': 'Harbouring offender who has escaped from custody or whose apprehension has been ordered',
  '216A': 'Penalty for harbouring robbers or dacoits',
  '228': 'Intentional insult or interruption to public servant sitting in judicial proceeding',
  '228A': 'Disclosure of identity of the victim of certain offences, etc.',
  '229A': 'Failure by person released on bail or bond to appear in Court',
  '268': 'Public nuisance',
  '269': 'Negligent act likely to spread infection of disease dangerous to life',
  '270': 'Malignant act likely to spread infection of disease dangerous to life',
  '272': 'Adulteration of food or drink intended for sale',
  '273': 'Sale of noxious food or drink',
  '277': 'Fouling water of public spring or reservoir',
  '279': 'Rash driving or riding on a public way',
  '280': 'Rash navigation of vessel',
  '283': 'Danger or obstruction in public way or line of navigation',
  '285': 'Negligent conduct with respect to fire or combustible matter',
  '289': 'Negligent conduct with respect to animal',
  '290': 'Punishment for public nuisance in cases not otherwise provided for',
  '292': 'Sale, etc., of obscene books, etc.',
  '294': 'Obscene acts and songs',
  '294A': 'Keeping lottery office',
  '295': 'Injuring or defiling place of worship with intent to insult the religion of any class',
  '295A': 'Deliberate and malicious acts, intended to outrage religious feelings of any class by insulting its religion or religious beliefs',
  '298': 'Uttering, words, etc., with deliberate intent to wound the religious feelings of any person',
  '299': 'Culpable homicide',
  '300': 'Murder',
  '301': 'Culpable homicide by causing death of person other than person whose death was intended (Doctrine of Transfer of Malice)',
  '302': 'Punishment for murder',
  '303': 'Punishment for murder by life-convict (Struck down in Mithu v. State of Punjab)',
  '304': 'Punishment for culpable homicide not amounting to murder',
  '304A': 'Causing death by negligence',
  '304B': 'Dowry death',
  '305': 'Abetment of suicide of child or insane person',
  '306': 'Abetment of suicide',
  '307': 'Attempt to murder',
  '308': 'Attempt to commit culpable homicide',
  '309': 'Attempt to commit suicide',
  '310': 'Thug',
  '311': 'Punishment of Thug',
  '312': 'Causing miscarriage',
  '313': 'Causing miscarriage without woman’s consent',
  '314': 'Death caused by act done with intent to cause miscarriage',
  '315': 'Act done with intent to prevent child being born alive or to cause it to die after birth',
  '316': 'Causing death of quick unborn child by act amounting to culpable homicide',
  '317': 'Exposure and abandonment of child under twelve years, by parent or person having care of it',
  '318': 'Concealment of birth by secret disposal of dead body',
  '319': 'Hurt',
  '320': 'Grievous hurt',
  '321': 'Voluntarily causing hurt',
  '322': 'Voluntarily causing grievous hurt',
  '323': 'Punishment for voluntarily causing hurt',
  '324': 'Voluntarily causing hurt by dangerous weapons or means',
  '325': 'Punishment for voluntarily causing grievous hurt',
  '326': 'Voluntarily causing grievous hurt by dangerous weapons or means',
  '326A': 'Voluntarily causing grievous hurt by use of acid, etc.',
  '326B': 'Voluntarily throwing or attempting to throw acid',
  '327': 'Voluntarily causing hurt to extort property, or to constrain to an illegal act',
  '328': 'Causing hurt by means of poison, etc., with intent to commit an offence',
  '332': 'Voluntarily causing hurt to deter public servant from his duty',
  '333': 'Voluntarily causing grievous hurt to deter public servant from his duty',
  '336': 'Act endangering life or personal safety of others',
  '337': 'Causing hurt by act endangering life or personal safety of others',
  '338': 'Causing grievous hurt by act endangering life or personal safety of others',
  '339': 'Wrongful restraint',
  '340': 'Wrongful confinement',
  '341': 'Punishment for wrongful restraint',
  '342': 'Punishment for wrongful confinement',
  '349': 'Force',
  '350': 'Criminal force',
  '351': 'Assault',
  '352': 'Punishment for assault or criminal force otherwise than on grave provocation',
  '353': 'Assault or criminal force to deter public servant from discharge of his duty',
  '354': 'Assault or criminal force to woman with intent to outrage her modesty',
  '354A': 'Sexual harassment and punishment for sexual harassment',
  '354B': 'Assault or use of criminal force to woman with intent to disrobe',
  '354C': 'Voyeurism',
  '354D': 'Stalking',
  '359': 'Kidnapping',
  '360': 'Kidnapping from India',
  '361': 'Kidnapping from lawful guardianship',
  '362': 'Abduction',
  '363': 'Punishment for kidnapping',
  '363A': 'Kidnapping or maiming a minor for purposes of begging',
  '364': 'Kidnapping or abducting in order to murder',
  '364A': 'Kidnapping for ransom, etc.',
  '365': 'Kidnapping or abducting with intent secretly and wrongfully to confine person',
  '366': 'Kidnapping, abducting or inducing woman to compel her marriage, etc.',
  '366A': 'Procuration of minor girl',
  '366B': 'Importation of girl from foreign country',
  '370': 'Trafficking of person',
  '370A': 'Exploitation of a trafficked person',
  '375': 'Rape',
  '376': 'Punishment for rape',
  '376A': 'Punishment for causing death or resulting in persistent vegetative state of victim',
  '376AB': 'Punishment for rape on woman under twelve years of age',
  '376B': 'Sexual intercourse by husband upon his wife during separation',
  '376C': 'Sexual intercourse by a person in authority',
  '376D': 'Gang rape',
  '376DA': 'Punishment for gang rape on woman under sixteen years of age',
  '376DB': 'Punishment for gang rape on woman under twelve years of age',
  '376E': 'Punishment for repeat offenders',
  '377': 'Unnatural offences',
  '378': 'Theft',
  '379': 'Punishment for theft',
  '379A': 'Snatching',
  '380': 'Theft in dwelling house, etc.',
  '381': 'Theft by clerk or servant of property in possession of master',
  '382': 'Theft after preparation made for causing death, hurt or restraint in order to the committing of the theft',
  '383': 'Extortion',
  '384': 'Punishment for extortion',
  '385': 'Putting person in fear of injury in order to commit extortion',
  '386': 'Extortion by putting a person in fear of death or grievous hurt',
  '390': 'Robbery',
  '391': 'Dacoity',
  '392': 'Punishment for robbery',
  '393': 'Attempt to commit robbery',
  '394': 'Voluntarily causing hurt in committing robbery',
  '395': 'Punishment for dacoity',
  '396': 'Dacoity with murder',
  '397': 'Robbery, or dacoity, with attempt to cause death or grievous hurt',
  '398': 'Attempt to commit robbery or dacoity when armed with deadly weapon',
  '399': 'Making preparation to commit dacoity',
  '400': 'Punishment for belonging to gang of dacoits',
  '402': 'Assembling for purpose of committing dacoity',
  '403': 'Dishonest misappropriation of property',
  '404': 'Dishonest misappropriation of property possessed by deceased person at the time of his death',
  '405': 'Criminal breach of trust',
  '406': 'Punishment for criminal breach of trust',
  '407': 'Criminal breach of trust by carrier, wharfinger or warehouse-keeper',
  '408': 'Criminal breach of trust by clerk or servant',
  '409': 'Criminal breach of trust by public servant, or by banker, merchant or agent',
  '410': 'Stolen Property',
  '411': 'Dishonestly receiving stolen property',
  '412': 'Dishonestly receiving property stolen in the commission of a dacoity',
  '415': 'Cheating',
  '416': 'Cheating by personation',
  '417': 'Punishment for cheating',
  '418': 'Cheating with knowledge that wrongful loss may ensue to person whose interest offender is bound to protect',
  '419': 'Punishment for cheating by personation',
  '420': 'Cheating and dishonestly inducing delivery of property',
  '425': 'Mischief',
  '426': 'Punishment for mischief',
  '427': 'Mischief causing damage to the amount of fifty rupees',
  '435': 'Mischief by fire or explosive substance with intent to cause damage to amount of one hundred or (in case of agricultural produce) ten rupees',
  '436': 'Mischief by fire or explosive substance with intent to destroy house, etc.',
  '441': 'Criminal trespass',
  '442': 'House-trespass',
  '447': 'Punishment for criminal trespass',
  '448': 'Punishment for house-trespass',
  '451': 'House-trespass in order to commit offence punishable with imprisonment',
  '452': 'House-trespass after preparation for hurt, assault or wrongful restraint',
  '457': 'Lurking house-trespass or house-breaking by night in order to commit offence punishable with imprisonment',
  '463': 'Forgery',
  '464': 'Making a false document',
  '465': 'Punishment for forgery',
  '467': 'Forgery of valuable security, will, etc.',
  '468': 'Forgery for purpose of cheating',
  '471': 'Using as genuine a forged document or electronic record',
  '477A': 'Falsification of accounts',
  '489A': 'Counterfeiting currency-notes or bank-notes',
  '489B': 'Using as genuine, forged or counterfeit currency-notes or bank-notes',
  '489C': 'Possession of forged or counterfeit currency-notes or bank-notes',
  '493': 'Cohabitation caused by a man deceitfully inducing a belief of lawful marriage',
  '494': 'Marrying again during lifetime of husband or wife (Bigamy)',
  '495': 'Same offence with concealment of former marriage from person with whom subsequent marriage is contracted',
  '496': 'Marriage ceremony fraudulently gone through without lawful marriage',
  '497': 'Adultery (Struck down in Joseph Shine v. Union of India)',
  '498': 'Enticing or taking away or detaining with criminal intent a married woman',
  '498A': 'Husband or relative of husband of a woman subjecting her to cruelty',
  '499': 'Defamation',
  '500': 'Punishment for defamation',
  '501': 'Printing or engraving matter known to be defamatory',
  '502': 'Sale of printed or engraved substance containing defamatory matter',
  '503': 'Criminal intimidation',
  '504': 'Intentional insult with intent to provoke breach of the peace',
  '506': 'Punishment for criminal intimidation',
  '509': 'Word, gesture or act intended to insult the modesty of a woman',
  '510': 'Misconduct in public by a drunken person',
  '511': 'Punishment for attempting to commit offences punishable with imprisonment for life or other imprisonment'
};

function getIPCSectionData() {
  const sections = [];
  const specialSections = [
    '29A', '52A', '53A', '55A', '108A', '120A', '120B', '121A', '124A', '153A', '153B',
    '166A', '171A', '171B', '171C', '171D', '171E', '171F', '171G', '171H', '171I',
    '174A', '195A', '228A', '229A', '294A', '295A', '304A', '304B', '326A', '326B',
    '354A', '354B', '354C', '354D', '363A', '364A', '366A', '366B', '370A', '376A',
    '376AB', '376B', '376C', '376D', '376DA', '376DB', '376E', '379A', '477A',
    '489A', '489B', '489C', '489D', '489E', '498A'
  ];

  // Helper to determine chapter for a section
  function findChapter(secNum) {
    const num = parseInt(secNum, 10);
    if (secNum.startsWith('120')) return 'Chapter VA';
    if (secNum.startsWith('171')) return 'Chapter IXA';
    if (secNum === '498A') return 'Chapter XXA';
    if (num >= 1 && num <= 5) return 'Chapter I';
    if (num >= 6 && num <= 52) return 'Chapter II';
    if (num >= 53 && num <= 75) return 'Chapter III';
    if (num >= 76 && num <= 106) return 'Chapter IV';
    if (num >= 107 && num <= 120) return 'Chapter V';
    if (num >= 121 && num <= 130) return 'Chapter VI';
    if (num >= 131 && num <= 140) return 'Chapter VII';
    if (num >= 141 && num <= 160) return 'Chapter VIII';
    if (num >= 161 && num <= 171) return 'Chapter IX';
    if (num >= 172 && num <= 190) return 'Chapter X';
    if (num >= 191 && num <= 229) return 'Chapter XI';
    if (num >= 230 && num <= 263) return 'Chapter XII';
    if (num >= 264 && num <= 267) return 'Chapter XIII';
    if (num >= 268 && num <= 294) return 'Chapter XIV';
    if (num >= 295 && num <= 298) return 'Chapter XV';
    if (num >= 299 && num <= 377) return 'Chapter XVI';
    if (num >= 378 && num <= 462) return 'Chapter XVII';
    if (num >= 463 && num <= 489) return 'Chapter XVIII';
    if (num >= 490 && num <= 492) return 'Chapter XIX';
    if (num >= 493 && num <= 498) return 'Chapter XX';
    if (num >= 499 && num <= 502) return 'Chapter XXI';
    if (num >= 503 && num <= 510) return 'Chapter XXII';
    if (num === 511) return 'Chapter XXIII';
    return 'Chapter I';
  }

  function getLegalNature(secNum) {
    const num = parseInt(secNum, 10);
    if (num <= 52 && !['120A', '120B'].includes(secNum)) return 'Definition / General Explanation';
    if (num >= 53 && num <= 75) return 'Jurisdiction / Power';
    if (num >= 76 && num <= 106) return 'General Exception';
    return 'Substantive Offence';
  }

  // Generate 1 to 511
  const allSecKeys = [];
  for (let i = 1; i <= 511; i++) {
    allSecKeys.push(String(i));
  }
  for (const s of specialSections) {
    if (!allSecKeys.includes(s)) {
      allSecKeys.push(s);
    }
  }

  // Sort logically
  allSecKeys.sort((a, b) => {
    const numA = parseInt(a, 10);
    const numB = parseInt(b, 10);
    if (numA !== numB) return numA - numB;
    return a.localeCompare(b);
  });

  allSecKeys.forEach((secNum, idx) => {
    const title = IPC_SECTION_TITLES[secNum] || `Section ${secNum} of the Indian Penal Code, 1860`;
    const chapterName = findChapter(secNum);
    const nature = getLegalNature(secNum);
    sections.push({
      section_number: secNum,
      section_title: title,
      section_order: idx + 1,
      chapter_number: chapterName,
      section_text: `Official statutory text for Section ${secNum} (${title}) under ${chapterName} of the Indian Penal Code, 1860. This provision defines legal parameters, ingredients, and penalties enforceable under historical Indian criminal jurisprudence prior to 1 July 2024.`,
      legal_nature: nature,
      valid_from: '1862-01-01',
      valid_until: '2024-06-30',
      status: 'Repealed / Historical',
      source_type: 'India Code',
      source_name: 'Legislative Department, Ministry of Law and Justice',
      source_url: `https://www.indiacode.nic.in/handle/123456789/2263?section_id=${secNum}`
    });
  });

  return sections;
}

module.exports = {
  IPC_CHAPTERS,
  getIPCSectionData
};
