'use strict';

/**
 * Verified Cross-Reference Matrix (Old Criminal Laws ↔ New Criminal Laws)
 * Source: Bureau of Police Research & Development (BPR&D), Ministry of Home Affairs, Government of India
 * https://bprd.nic.in/
 */

const SECTION_MAPPINGS = [
  // ==========================================
  // IPC (1860) ↔ BNS (2023) Mappings
  // ==========================================
  { from_act: 'IPC_1860', from_sec: '1', to_act: 'BNS_2023', to_sec: '1', relation_type: 'CORRESPONDS_TO', notes: 'Title, extent and commencement' },
  { from_act: 'IPC_1860', from_sec: '2', to_act: 'BNS_2023', to_sec: '1', relation_type: 'CORRESPONDS_TO', notes: 'Punishment of offences committed within India' },
  { from_act: 'IPC_1860', from_sec: '34', to_act: 'BNS_2023', to_sec: '3', relation_type: 'MODIFIED_BY', notes: 'Acts done by several persons in furtherance of common intention is now consolidated under Section 3(5) BNS' },
  { from_act: 'IPC_1860', from_sec: '53', to_act: 'BNS_2023', to_sec: '4', relation_type: 'MODIFIED_BY', notes: 'Punishments categorized, newly introducing Community Service as a statutory penal measure' },
  { from_act: 'IPC_1860', from_sec: '76', to_act: 'BNS_2023', to_sec: '14', relation_type: 'CORRESPONDS_TO', notes: 'Act done by a person bound, or by mistake of fact believing himself bound, by law' },
  { from_act: 'IPC_1860', from_sec: '77', to_act: 'BNS_2023', to_sec: '15', relation_type: 'CORRESPONDS_TO', notes: 'Act of Judge when acting judicially' },
  { from_act: 'IPC_1860', from_sec: '79', to_act: 'BNS_2023', to_sec: '17', relation_type: 'CORRESPONDS_TO', notes: 'Act done by person justified by law' },
  { from_act: 'IPC_1860', from_sec: '80', to_act: 'BNS_2023', to_sec: '18', relation_type: 'CORRESPONDS_TO', notes: 'Accident in doing a lawful act' },
  { from_act: 'IPC_1860', from_sec: '82', to_act: 'BNS_2023', to_sec: '20', relation_type: 'CORRESPONDS_TO', notes: 'Act of child under seven years (Doli incapax)' },
  { from_act: 'IPC_1860', from_sec: '83', to_act: 'BNS_2023', to_sec: '21', relation_type: 'CORRESPONDS_TO', notes: 'Act of child above seven and under twelve of immature understanding' },
  { from_act: 'IPC_1860', from_sec: '84', to_act: 'BNS_2023', to_sec: '22', relation_type: 'CORRESPONDS_TO', notes: 'Act of person of unsound mind (McNaughten rule of legal insanity)' },
  { from_act: 'IPC_1860', from_sec: '85', to_act: 'BNS_2023', to_sec: '23', relation_type: 'CORRESPONDS_TO', notes: 'Involuntary intoxication defence' },
  { from_act: 'IPC_1860', from_sec: '96', to_act: 'BNS_2023', to_sec: '34', relation_type: 'CORRESPONDS_TO', notes: 'Things done in private defence' },
  { from_act: 'IPC_1860', from_sec: '100', to_act: 'BNS_2023', to_sec: '38', relation_type: 'CORRESPONDS_TO', notes: 'When right of private defence of body extends to causing death' },
  { from_act: 'IPC_1860', from_sec: '103', to_act: 'BNS_2023', to_sec: '41', relation_type: 'CORRESPONDS_TO', notes: 'When right of private defence of property extends to causing death' },
  { from_act: 'IPC_1860', from_sec: '107', to_act: 'BNS_2023', to_sec: '45', relation_type: 'CORRESPONDS_TO', notes: 'Abetment of a thing' },
  { from_act: 'IPC_1860', from_sec: '109', to_act: 'BNS_2023', to_sec: '49', relation_type: 'CORRESPONDS_TO', notes: 'Punishment of abetment if act abetted is committed in consequence' },
  { from_act: 'IPC_1860', from_sec: '120B', to_act: 'BNS_2023', to_sec: '61', relation_type: 'MODIFIED_BY', notes: 'Criminal conspiracy consolidated into Section 61 BNS' },
  { from_act: 'IPC_1860', from_sec: '121', to_act: 'BNS_2023', to_sec: '147', relation_type: 'CORRESPONDS_TO', notes: 'Waging or attempting to wage war against Government of India' },
  { from_act: 'IPC_1860', from_sec: '124A', to_act: 'BNS_2023', to_sec: '152', relation_type: 'MODIFIED_BY', notes: 'Sedition repealed and replaced by Act endangering sovereignty, unity and integrity of India' },
  { from_act: 'IPC_1860', from_sec: '141', to_act: 'BNS_2023', to_sec: '189', relation_type: 'CORRESPONDS_TO', notes: 'Unlawful assembly definition' },
  { from_act: 'IPC_1860', from_sec: '149', to_act: 'BNS_2023', to_sec: '190', relation_type: 'CORRESPONDS_TO', notes: 'Every member of unlawful assembly guilty of offence committed in prosecution of common object' },
  { from_act: 'IPC_1860', from_sec: '153A', to_act: 'BNS_2023', to_sec: '196', relation_type: 'CORRESPONDS_TO', notes: 'Promoting enmity between different groups' },
  { from_act: 'IPC_1860', from_sec: '153B', to_act: 'BNS_2023', to_sec: '197', relation_type: 'CORRESPONDS_TO', notes: 'Imputations, assertions prejudicial to national integration' },
  { from_act: 'IPC_1860', from_sec: '188', to_act: 'BNS_2023', to_sec: '223', relation_type: 'CORRESPONDS_TO', notes: 'Disobedience to order duly promulgated by public servant' },
  { from_act: 'IPC_1860', from_sec: '191', to_act: 'BNS_2023', to_sec: '227', relation_type: 'CORRESPONDS_TO', notes: 'Giving false evidence (Perjury)' },
  { from_act: 'IPC_1860', from_sec: '192', to_act: 'BNS_2023', to_sec: '228', relation_type: 'CORRESPONDS_TO', notes: 'Fabricating false evidence' },
  { from_act: 'IPC_1860', from_sec: '193', to_act: 'BNS_2023', to_sec: '229', relation_type: 'CORRESPONDS_TO', notes: 'Punishment for false evidence' },
  { from_act: 'IPC_1860', from_sec: '201', to_act: 'BNS_2023', to_sec: '238', relation_type: 'CORRESPONDS_TO', notes: 'Causing disappearance of evidence or giving false information to screen offender' },
  { from_act: 'IPC_1860', from_sec: '268', to_act: 'BNS_2023', to_sec: '270', relation_type: 'CORRESPONDS_TO', notes: 'Public nuisance' },
  { from_act: 'IPC_1860', from_sec: '279', to_act: 'BNS_2023', to_sec: '281', relation_type: 'CORRESPONDS_TO', notes: 'Rash driving or riding on a public way' },
  { from_act: 'IPC_1860', from_sec: '295A', to_act: 'BNS_2023', to_sec: '299', relation_type: 'CORRESPONDS_TO', notes: 'Deliberate and malicious acts intended to outrage religious feelings' },
  { from_act: 'IPC_1860', from_sec: '299', to_act: 'BNS_2023', to_sec: '100', relation_type: 'CORRESPONDS_TO', notes: 'Culpable homicide definition' },
  { from_act: 'IPC_1860', from_sec: '300', to_act: 'BNS_2023', to_sec: '101', relation_type: 'CORRESPONDS_TO', notes: 'Murder definition and exceptions' },
  { from_act: 'IPC_1860', from_sec: '302', to_act: 'BNS_2023', to_sec: '103', relation_type: 'MODIFIED_BY', notes: 'Punishment for murder; Section 103(2) BNS also explicitly penalizes mob lynching on grounds of race, caste, etc.' },
  { from_act: 'IPC_1860', from_sec: '304', to_act: 'BNS_2023', to_sec: '105', relation_type: 'CORRESPONDS_TO', notes: 'Punishment for culpable homicide not amounting to murder' },
  { from_act: 'IPC_1860', from_sec: '304A', to_act: 'BNS_2023', to_sec: '106', relation_type: 'MODIFIED_BY', notes: 'Causing death by negligence; Sec 106(2) provides enhanced 10-year punishment for hit-and-run without reporting' },
  { from_act: 'IPC_1860', from_sec: '304B', to_act: 'BNS_2023', to_sec: '80', relation_type: 'REPLACED_BY', notes: 'Dowry death shifted into Chapter V (Offences against women and children)' },
  { from_act: 'IPC_1860', from_sec: '306', to_act: 'BNS_2023', to_sec: '108', relation_type: 'CORRESPONDS_TO', notes: 'Abetment of suicide' },
  { from_act: 'IPC_1860', from_sec: '307', to_act: 'BNS_2023', to_sec: '109', relation_type: 'CORRESPONDS_TO', notes: 'Attempt to murder' },
  { from_act: 'IPC_1860', from_sec: '308', to_act: 'BNS_2023', to_sec: '110', relation_type: 'CORRESPONDS_TO', notes: 'Attempt to commit culpable homicide' },
  { from_act: 'IPC_1860', from_sec: '319', to_act: 'BNS_2023', to_sec: '114', relation_type: 'CORRESPONDS_TO', notes: 'Hurt defined' },
  { from_act: 'IPC_1860', from_sec: '320', to_act: 'BNS_2023', to_sec: '116', relation_type: 'CORRESPONDS_TO', notes: 'Grievous hurt defined' },
  { from_act: 'IPC_1860', from_sec: '323', to_act: 'BNS_2023', to_sec: '115', relation_type: 'CORRESPONDS_TO', notes: 'Punishment for voluntarily causing hurt' },
  { from_act: 'IPC_1860', from_sec: '325', to_act: 'BNS_2023', to_sec: '117', relation_type: 'CORRESPONDS_TO', notes: 'Punishment for voluntarily causing grievous hurt' },
  { from_act: 'IPC_1860', from_sec: '326A', to_act: 'BNS_2023', to_sec: '124', relation_type: 'CORRESPONDS_TO', notes: 'Voluntarily causing grievous hurt by use of acid' },
  { from_act: 'IPC_1860', from_sec: '339', to_act: 'BNS_2023', to_sec: '126', relation_type: 'CORRESPONDS_TO', notes: 'Wrongful restraint' },
  { from_act: 'IPC_1860', from_sec: '340', to_act: 'BNS_2023', to_sec: '126', relation_type: 'CORRESPONDS_TO', notes: 'Wrongful confinement' },
  { from_act: 'IPC_1860', from_sec: '341', to_act: 'BNS_2023', to_sec: '126', relation_type: 'CORRESPONDS_TO', notes: 'Punishment for wrongful restraint' },
  { from_act: 'IPC_1860', from_sec: '342', to_act: 'BNS_2023', to_sec: '127', relation_type: 'CORRESPONDS_TO', notes: 'Punishment for wrongful confinement' },
  { from_act: 'IPC_1860', from_sec: '351', to_act: 'BNS_2023', to_sec: '130', relation_type: 'CORRESPONDS_TO', notes: 'Assault defined' },
  { from_act: 'IPC_1860', from_sec: '353', to_act: 'BNS_2023', to_sec: '132', relation_type: 'CORRESPONDS_TO', notes: 'Assault to deter public servant from discharge of duty' },
  { from_act: 'IPC_1860', from_sec: '354', to_act: 'BNS_2023', to_sec: '74', relation_type: 'REPLACED_BY', notes: 'Assault to woman with intent to outrage modesty shifted to Chapter V' },
  { from_act: 'IPC_1860', from_sec: '354A', to_act: 'BNS_2023', to_sec: '75', relation_type: 'REPLACED_BY', notes: 'Sexual harassment shifted to Section 75 BNS' },
  { from_act: 'IPC_1860', from_sec: '354C', to_act: 'BNS_2023', to_sec: '77', relation_type: 'REPLACED_BY', notes: 'Voyeurism shifted to Section 77 BNS' },
  { from_act: 'IPC_1860', from_sec: '354D', to_act: 'BNS_2023', to_sec: '78', relation_type: 'REPLACED_BY', notes: 'Stalking shifted to Section 78 BNS' },
  { from_act: 'IPC_1860', from_sec: '363', to_act: 'BNS_2023', to_sec: '137', relation_type: 'CORRESPONDS_TO', notes: 'Punishment for kidnapping' },
  { from_act: 'IPC_1860', from_sec: '364A', to_act: 'BNS_2023', to_sec: '140', relation_type: 'CORRESPONDS_TO', notes: 'Kidnapping for ransom' },
  { from_act: 'IPC_1860', from_sec: '370', to_act: 'BNS_2023', to_sec: '143', relation_type: 'CORRESPONDS_TO', notes: 'Trafficking of person' },
  { from_act: 'IPC_1860', from_sec: '375', to_act: 'BNS_2023', to_sec: '63', relation_type: 'REPLACED_BY', notes: 'Rape definition consolidated in Section 63 BNS' },
  { from_act: 'IPC_1860', from_sec: '376', to_act: 'BNS_2023', to_sec: '64', relation_type: 'REPLACED_BY', notes: 'Punishment for rape consolidated in Section 64 BNS' },
  { from_act: 'IPC_1860', from_sec: '376D', to_act: 'BNS_2023', to_sec: '70', relation_type: 'REPLACED_BY', notes: 'Gang rape provisions consolidated in Section 70 BNS' },
  { from_act: 'IPC_1860', from_sec: '378', to_act: 'BNS_2023', to_sec: '303', relation_type: 'CORRESPONDS_TO', notes: 'Theft defined' },
  { from_act: 'IPC_1860', from_sec: '379', to_act: 'BNS_2023', to_sec: '303', relation_type: 'CORRESPONDS_TO', notes: 'Punishment for theft' },
  { from_act: 'IPC_1860', from_sec: '379A', to_act: 'BNS_2023', to_sec: '304', relation_type: 'MODIFIED_BY', notes: 'Snatching newly defined as a distinct statutory offence under Section 304 BNS' },
  { from_act: 'IPC_1860', from_sec: '380', to_act: 'BNS_2023', to_sec: '305', relation_type: 'CORRESPONDS_TO', notes: 'Theft in dwelling house or conveyance' },
  { from_act: 'IPC_1860', from_sec: '383', to_act: 'BNS_2023', to_sec: '308', relation_type: 'CORRESPONDS_TO', notes: 'Extortion defined' },
  { from_act: 'IPC_1860', from_sec: '390', to_act: 'BNS_2023', to_sec: '309', relation_type: 'CORRESPONDS_TO', notes: 'Robbery defined' },
  { from_act: 'IPC_1860', from_sec: '391', to_act: 'BNS_2023', to_sec: '310', relation_type: 'CORRESPONDS_TO', notes: 'Dacoity defined' },
  { from_act: 'IPC_1860', from_sec: '392', to_act: 'BNS_2023', to_sec: '309', relation_type: 'CORRESPONDS_TO', notes: 'Punishment for robbery' },
  { from_act: 'IPC_1860', from_sec: '395', to_act: 'BNS_2023', to_sec: '310', relation_type: 'CORRESPONDS_TO', notes: 'Punishment for dacoity' },
  { from_act: 'IPC_1860', from_sec: '405', to_act: 'BNS_2023', to_sec: '316', relation_type: 'CORRESPONDS_TO', notes: 'Criminal breach of trust defined' },
  { from_act: 'IPC_1860', from_sec: '406', to_act: 'BNS_2023', to_sec: '316', relation_type: 'CORRESPONDS_TO', notes: 'Punishment for criminal breach of trust' },
  { from_act: 'IPC_1860', from_sec: '411', to_act: 'BNS_2023', to_sec: '317', relation_type: 'CORRESPONDS_TO', notes: 'Dishonestly receiving stolen property' },
  { from_act: 'IPC_1860', from_sec: '415', to_act: 'BNS_2023', to_sec: '318', relation_type: 'CORRESPONDS_TO', notes: 'Cheating defined' },
  { from_act: 'IPC_1860', from_sec: '420', to_act: 'BNS_2023', to_sec: '318', relation_type: 'MODIFIED_BY', notes: 'Cheating and dishonestly inducing delivery of property consolidated under Section 318(4) BNS' },
  { from_act: 'IPC_1860', from_sec: '425', to_act: 'BNS_2023', to_sec: '324', relation_type: 'CORRESPONDS_TO', notes: 'Mischief defined' },
  { from_act: 'IPC_1860', from_sec: '441', to_act: 'BNS_2023', to_sec: '329', relation_type: 'CORRESPONDS_TO', notes: 'Criminal trespass defined' },
  { from_act: 'IPC_1860', from_sec: '463', to_act: 'BNS_2023', to_sec: '336', relation_type: 'CORRESPONDS_TO', notes: 'Forgery defined' },
  { from_act: 'IPC_1860', from_sec: '464', to_act: 'BNS_2023', to_sec: '335', relation_type: 'CORRESPONDS_TO', notes: 'Making false document' },
  { from_act: 'IPC_1860', from_sec: '468', to_act: 'BNS_2023', to_sec: '338', relation_type: 'CORRESPONDS_TO', notes: 'Forgery for purpose of cheating' },
  { from_act: 'IPC_1860', from_sec: '471', to_act: 'BNS_2023', to_sec: '340', relation_type: 'CORRESPONDS_TO', notes: 'Using as genuine a forged document or electronic record' },
  { from_act: 'IPC_1860', from_sec: '498A', to_act: 'BNS_2023', to_sec: '85', relation_type: 'REPLACED_BY', notes: 'Cruelty by husband or relatives replaced by Section 85 (punishment) and Section 86 (definition) BNS' },
  { from_act: 'IPC_1860', from_sec: '499', to_act: 'BNS_2023', to_sec: '356', relation_type: 'MODIFIED_BY', notes: 'Defamation consolidated under Section 356 BNS; allows community service' },
  { from_act: 'IPC_1860', from_sec: '500', to_act: 'BNS_2023', to_sec: '356', relation_type: 'CORRESPONDS_TO', notes: 'Punishment for defamation' },
  { from_act: 'IPC_1860', from_sec: '504', to_act: 'BNS_2023', to_sec: '352', relation_type: 'CORRESPONDS_TO', notes: 'Intentional insult to provoke breach of peace' },
  { from_act: 'IPC_1860', from_sec: '506', to_act: 'BNS_2023', to_sec: '351', relation_type: 'CORRESPONDS_TO', notes: 'Punishment for criminal intimidation' },
  { from_act: 'IPC_1860', from_sec: '509', to_act: 'BNS_2023', to_sec: '79', relation_type: 'REPLACED_BY', notes: 'Word, gesture or act intended to insult modesty of woman shifted to Section 79 BNS' },
  { from_act: 'IPC_1860', from_sec: '511', to_act: 'BNS_2023', to_sec: '62', relation_type: 'MODIFIED_BY', notes: 'General attempt to commit offences consolidated under Section 62 BNS' },

  // ==========================================
  // CrPC (1973) ↔ BNSS (2023) Mappings
  // ==========================================
  { from_act: 'CRPC_1973', from_sec: '41', to_act: 'BNSS_2023', to_sec: '35', relation_type: 'MODIFIED_BY', notes: 'Arrest without warrant; requires prior permission for elderly/infirm in minor cases and notice' },
  { from_act: 'CRPC_1973', from_sec: '41A', to_act: 'BNSS_2023', to_sec: '35', relation_type: 'MODIFIED_BY', notes: 'Notice of appearance consolidated directly into Section 35(3) BNSS' },
  { from_act: 'CRPC_1973', from_sec: '41B', to_act: 'BNSS_2023', to_sec: '37', relation_type: 'CORRESPONDS_TO', notes: 'Procedure of arrest and duties of officer making arrest' },
  { from_act: 'CRPC_1973', from_sec: '41D', to_act: 'BNSS_2023', to_sec: '38', relation_type: 'CORRESPONDS_TO', notes: 'Right to meet advocate during interrogation' },
  { from_act: 'CRPC_1973', from_sec: '57', to_act: 'BNSS_2023', to_sec: '58', relation_type: 'CORRESPONDS_TO', notes: 'Person arrested not to be detained more than 24 hours' },
  { from_act: 'CRPC_1973', from_sec: '61', to_act: 'BNSS_2023', to_sec: '63', relation_type: 'MODIFIED_BY', notes: 'Form of summons; expressly incorporates electronic summons via SMS/email' },
  { from_act: 'CRPC_1973', from_sec: '82', to_act: 'BNSS_2023', to_sec: '84', relation_type: 'CORRESPONDS_TO', notes: 'Proclamation for person absconding' },
  { from_act: 'CRPC_1973', from_sec: '83', to_act: 'BNSS_2023', to_sec: '85', relation_type: 'CORRESPONDS_TO', notes: 'Attachment of property of absconding person' },
  { from_act: 'CRPC_1973', from_sec: '91', to_act: 'BNSS_2023', to_sec: '94', relation_type: 'CORRESPONDS_TO', notes: 'Summons to produce document or thing' },
  { from_act: 'CRPC_1973', from_sec: '100', to_act: 'BNSS_2023', to_sec: '105', relation_type: 'MODIFIED_BY', notes: 'Search procedure; Section 105 BNSS mandates audio-video recording of search and seizure' },
  { from_act: 'CRPC_1973', from_sec: '125', to_act: 'BNSS_2023', to_sec: '144', relation_type: 'CORRESPONDS_TO', notes: 'Maintenance of wives, children and parents' },
  { from_act: 'CRPC_1973', from_sec: '144', to_act: 'BNSS_2023', to_sec: '163', relation_type: 'CORRESPONDS_TO', notes: 'Urgent cases of nuisance or apprehended danger' },
  { from_act: 'CRPC_1973', from_sec: '154', to_act: 'BNSS_2023', to_sec: '173', relation_type: 'MODIFIED_BY', notes: 'FIR; Section 173 BNSS expressly incorporates Zero FIR and electronic FIR' },
  { from_act: 'CRPC_1973', from_sec: '156', to_act: 'BNSS_2023', to_sec: '175', relation_type: 'CORRESPONDS_TO', notes: 'Investigation of cognizable case' },
  { from_act: 'CRPC_1973', from_sec: '157', to_act: 'BNSS_2023', to_sec: '176', relation_type: 'MODIFIED_BY', notes: 'Mandatory forensic investigation for offences punishable with 7 years or more' },
  { from_act: 'CRPC_1973', from_sec: '161', to_act: 'BNSS_2023', to_sec: '180', relation_type: 'MODIFIED_BY', notes: 'Examination of witnesses by police; permits audio-video recording' },
  { from_act: 'CRPC_1973', from_sec: '164', to_act: 'BNSS_2023', to_sec: '183', relation_type: 'MODIFIED_BY', notes: 'Recording confessions and statements before Magistrate; audio-video means allowed' },
  { from_act: 'CRPC_1973', from_sec: '167', to_act: 'BNSS_2023', to_sec: '187', relation_type: 'MODIFIED_BY', notes: 'Remand and default bail; 15 days police custody can be taken in tranches across 40/60 days' },
  { from_act: 'CRPC_1973', from_sec: '173', to_act: 'BNSS_2023', to_sec: '193', relation_type: 'MODIFIED_BY', notes: 'Chargesheet / final report; mandates electronic progress updates to informant within 90 days' },
  { from_act: 'CRPC_1973', from_sec: '190', to_act: 'BNSS_2023', to_sec: '210', relation_type: 'CORRESPONDS_TO', notes: 'Cognizance of offences by Magistrates' },
  { from_act: 'CRPC_1973', from_sec: '197', to_act: 'BNSS_2023', to_sec: '218', relation_type: 'MODIFIED_BY', notes: 'Sanction for prosecution of public servants; requires decision within 120 days' },
  { from_act: 'CRPC_1973', from_sec: '200', to_act: 'BNSS_2023', to_sec: '223', relation_type: 'MODIFIED_BY', notes: 'Examination of complainant; requires giving opportunity to accused before cognizance' },
  { from_act: 'CRPC_1973', from_sec: '207', to_act: 'BNSS_2023', to_sec: '230', relation_type: 'MODIFIED_BY', notes: 'Supply of copies; mandates electronic supply within 14 days' },
  { from_act: 'CRPC_1973', from_sec: '227', to_act: 'BNSS_2023', to_sec: '250', relation_type: 'MODIFIED_BY', notes: 'Discharge in Sessions trial; application to be filed within 60 days of commitment' },
  { from_act: 'CRPC_1973', from_sec: '228', to_act: 'BNSS_2023', to_sec: '251', relation_type: 'MODIFIED_BY', notes: 'Framing of charge; charges to be framed within 60 days of first hearing' },
  { from_act: 'CRPC_1973', from_sec: '309', to_act: 'BNSS_2023', to_sec: '346', relation_type: 'MODIFIED_BY', notes: 'Strict limit on adjournments; maximum of 2 adjournments to prevent delay' },
  { from_act: 'CRPC_1973', from_sec: '313', to_act: 'BNSS_2023', to_sec: '351', relation_type: 'MODIFIED_BY', notes: 'Examination of accused; permits audio-video electronic means' },
  { from_act: 'CRPC_1973', from_sec: '320', to_act: 'BNSS_2023', to_sec: '359', relation_type: 'CORRESPONDS_TO', notes: 'Compounding of offences' },
  { from_act: 'CRPC_1973', from_sec: '353', to_act: 'BNSS_2023', to_sec: '392', relation_type: 'MODIFIED_BY', notes: 'Judgment; must be pronounced within 30 to 45 days after termination of arguments' },
  { from_act: 'CRPC_1973', from_sec: '436A', to_act: 'BNSS_2023', to_sec: '479', relation_type: 'MODIFIED_BY', notes: 'Undertrial detention maximum; first-time offenders eligible on one-third period' },
  { from_act: 'CRPC_1973', from_sec: '437', to_act: 'BNSS_2023', to_sec: '480', relation_type: 'CORRESPONDS_TO', notes: 'Bail in non-bailable offences' },
  { from_act: 'CRPC_1973', from_sec: '438', to_act: 'BNSS_2023', to_sec: '482', relation_type: 'CORRESPONDS_TO', notes: 'Anticipatory bail' },
  { from_act: 'CRPC_1973', from_sec: '439', to_act: 'BNSS_2023', to_sec: '483', relation_type: 'CORRESPONDS_TO', notes: 'Special powers of High Court / Sessions Court regarding bail' },
  { from_act: 'CRPC_1973', from_sec: '482', to_act: 'BNSS_2023', to_sec: '528', relation_type: 'CORRESPONDS_TO', notes: 'Inherent powers of High Court preserved in Section 528 BNSS' },

  // ==========================================
  // IEA (1872) ↔ BSA (2023) Mappings
  // ==========================================
  { from_act: 'IEA_1872', from_sec: '3', to_act: 'BSA_2023', to_sec: '2', relation_type: 'MODIFIED_BY', notes: 'Definitions; adds electronic and digital records, electronic signatures' },
  { from_act: 'IEA_1872', from_sec: '6', to_act: 'BSA_2023', to_sec: '4', relation_type: 'CORRESPONDS_TO', notes: 'Res Gestae (Facts forming part of same transaction)' },
  { from_act: 'IEA_1872', from_sec: '8', to_act: 'BSA_2023', to_sec: '6', relation_type: 'CORRESPONDS_TO', notes: 'Motive, preparation and previous or subsequent conduct' },
  { from_act: 'IEA_1872', from_sec: '11', to_act: 'BSA_2023', to_sec: '9', relation_type: 'CORRESPONDS_TO', notes: 'Plea of Alibi' },
  { from_act: 'IEA_1872', from_sec: '17', to_act: 'BSA_2023', to_sec: '15', relation_type: 'CORRESPONDS_TO', notes: 'Admission defined' },
  { from_act: 'IEA_1872', from_sec: '24', to_act: 'BSA_2023', to_sec: '22', relation_type: 'CORRESPONDS_TO', notes: 'Confession caused by inducement, threat or promise' },
  { from_act: 'IEA_1872', from_sec: '25', to_act: 'BSA_2023', to_sec: '23', relation_type: 'CORRESPONDS_TO', notes: 'Confession to police officer' },
  { from_act: 'IEA_1872', from_sec: '27', to_act: 'BSA_2023', to_sec: '23', relation_type: 'MODIFIED_BY', notes: 'Discovery / Recovery proviso consolidated directly into Section 23 BSA' },
  { from_act: 'IEA_1872', from_sec: '32', to_act: 'BSA_2023', to_sec: '26', relation_type: 'CORRESPONDS_TO', notes: 'Dying declaration and statements of dead persons' },
  { from_act: 'IEA_1872', from_sec: '45', to_act: 'BSA_2023', to_sec: '39', relation_type: 'CORRESPONDS_TO', notes: 'Opinions of experts' },
  { from_act: 'IEA_1872', from_sec: '59', to_act: 'BSA_2023', to_sec: '54', relation_type: 'CORRESPONDS_TO', notes: 'Proof of facts by oral evidence' },
  { from_act: 'IEA_1872', from_sec: '60', to_act: 'BSA_2023', to_sec: '55', relation_type: 'CORRESPONDS_TO', notes: 'Oral evidence must be direct (Rule against Hearsay)' },
  { from_act: 'IEA_1872', from_sec: '62', to_act: 'BSA_2023', to_sec: '57', relation_type: 'MODIFIED_BY', notes: 'Primary evidence; explicitly recognizes electronic and digital records as primary evidence' },
  { from_act: 'IEA_1872', from_sec: '63', to_act: 'BSA_2023', to_sec: '58', relation_type: 'CORRESPONDS_TO', notes: 'Secondary evidence' },
  { from_act: 'IEA_1872', from_sec: '65B', to_act: 'BSA_2023', to_sec: '63', relation_type: 'MODIFIED_BY', notes: 'Electronic certificate admissibility standard; updated schedule and format under Section 63 BSA' },
  { from_act: 'IEA_1872', from_sec: '101', to_act: 'BSA_2023', to_sec: '104', relation_type: 'CORRESPONDS_TO', notes: 'Burden of proof' },
  { from_act: 'IEA_1872', from_sec: '106', to_act: 'BSA_2023', to_sec: '109', relation_type: 'CORRESPONDS_TO', notes: 'Burden of proving fact especially within knowledge' },
  { from_act: 'IEA_1872', from_sec: '113B', to_act: 'BSA_2023', to_sec: '118', relation_type: 'CORRESPONDS_TO', notes: 'Presumption as to dowry death' },
  { from_act: 'IEA_1872', from_sec: '114A', to_act: 'BSA_2023', to_sec: '119', relation_type: 'CORRESPONDS_TO', notes: 'Presumption as to absence of consent in rape prosecution' },
  { from_act: 'IEA_1872', from_sec: '118', to_act: 'BSA_2023', to_sec: '124', relation_type: 'CORRESPONDS_TO', notes: 'Competency of witnesses' },
  { from_act: 'IEA_1872', from_sec: '126', to_act: 'BSA_2023', to_sec: '132', relation_type: 'CORRESPONDS_TO', notes: 'Professional communications (Attorney-client privilege)' },
  { from_act: 'IEA_1872', from_sec: '137', to_act: 'BSA_2023', to_sec: '141', relation_type: 'CORRESPONDS_TO', notes: 'Examination-in-chief, Cross-examination, Re-examination' },
  { from_act: 'IEA_1872', from_sec: '138', to_act: 'BSA_2023', to_sec: '142', relation_type: 'CORRESPONDS_TO', notes: 'Order of examinations' },
  { from_act: 'IEA_1872', from_sec: '145', to_act: 'BSA_2023', to_sec: '148', relation_type: 'CORRESPONDS_TO', notes: 'Cross-examination as to previous statements in writing' },
  { from_act: 'IEA_1872', from_sec: '154', to_act: 'BSA_2023', to_sec: '157', relation_type: 'CORRESPONDS_TO', notes: 'Hostile witness examination' },
  { from_act: 'IEA_1872', from_sec: '165', to_act: 'BSA_2023', to_sec: '168', relation_type: 'CORRESPONDS_TO', notes: 'Judge’s power to put questions or order production' }
];

module.exports = {
  SECTION_MAPPINGS
};
